### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by quangv** [jaywcjlove/iNotify#2]
I'm getting a build error after `npm install title-notify --save`

```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Quang/dev/consulting/jason_maclulich/virtwebclient/node_modules/contextify
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
virt-web-prototype-doctor@0.0.3 /Users/Quang/dev/consulting/jason_maclulich/virtwebclient
└── title-notify@1.0.9 

npm WARN EPACKAGEJSON virt-web-prototype-doctor@0.0.3 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "title-notify" "--save"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Quang/dev/consulting/jason_maclulich/virtwebclient/npm-debug.log
```

wonder if it's because I recently upgraded to node 4.x ?

**Comment by jaywcjlove** [comment]
@quangv I recently upgraded to version 4.x node, but no build problem . Run `npm install && gulp build` command.
